[tools]
"aqua:github/copilot-cli" = "latest"
"aqua:k1LoW/mo" = "latest"
"aqua:ogham/exa" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bat = "latest"
claude = "latest"
codex = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
node = "25.2.1"
rg = "latest"
ripgrep = "latest"
sd = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
